### ISSUE TITLE
Property bags incorrectly modelled

### ISSUE THREAD

**Issue by reynir** [gborough/sarif#10]
Dear @gborough,

Thank you for this piece of software. I started evaluating it and I hope you don't mind me quite a few PRs and issues.

I noticed the property bag object is modelled as `(string * string) list`, but the specification  allows for any json value and not just strings. I would model it as `(string * Yojson.Basic.t) list`. This results in a stronger dependency on yojson though. What do you think?

I am happy to work on this if you like. But before I work on it I would like to hear your opinion on reducing the dependency cone and removing core as a dependency altogether (a continuation of #6). This would also require using something else than re2 (for example re) as it depends on core and many other packages.

**Comment by gborough** [comment]
@reynir Thanks for raising these issues, really appreciate your effort.

1. Regarding property bag, I was largely reading off the jsonschema and it describes this item as "Key/value pairs that provide additional information about the object" with item type as "string". Going through the spec earlier on this item for the first I see it does mention the type being either json types or string. I am leaning towards using just string since it's a super type of any  Yojson type strings, the producers and consumers of this type can always freely decide what to do with it. I just trawled through some other implementations in different languages and they all seem to be based on strings:

rust: https://docs.rs/serde-sarif/latest/serde_sarif/sarif/struct.PropertyBag.html
golang: https://github.com/owenrumney/go-sarif/blob/v1.1.1/sarif/properties.go#L5
java: https://docs.pmd-code.org/apidocs/pmd-core/6.46.0/net/sourceforge/pmd/renderers/internal/sarif/SarifLog.PropertyBag.html

I think I need to evaluate using Yojson types a little bit more and get back to you later

2. As for reducing dependencies I am all for it, in fact the first iteration was written without core and re2. I chose re2 in the last minute because it's considered to be bit safe and performant. But since the regex used here are very simple I don't see any issues using re. Using core is bit overkill too, dev dependency is enough. I am happy for you to keep working on this :)

**Comment by reynir** [comment]
> 1. Regarding property bag, I was largely reading off the jsonschema and it describes this item as "Key/value pairs that provide additional information about the object" with item type as "string". Going through the spec earlier on this item for the first I see it does mention the type being either json types or string. I am leaning towards using just string since it's a super type of any  Yojson type strings, the producers and consumers of this type can always freely decide what to do with it. I just trawled through some other implementations in different languages and they all seem to be based on strings:
> 
> 
> rust: https://docs.rs/serde-sarif/latest/serde_sarif/sarif/struct.PropertyBag.html golang: https://github.com/owenrumney/go-sarif/blob/v1.1.1/sarif/properties.go#L5 java: https://docs.pmd-code.org/apidocs/pmd-core/6.46.0/net/sourceforge/pmd/renderers/internal/sarif/SarifLog.PropertyBag.html

What I need to populate the property bag with is strings but also a property `tags` that is a list of strings. I can see that the `tags` property in the property bag has special status (see §3.8.2.2). Maybe the confusion stems from both the rust and java implementations implementing the special status of the `tags` property. Otherwise the [rust](https://docs.rs/serde-sarif/latest/serde_sarif/sarif/struct.PropertyBag.html#structfield.additional_properties) and [go](https://github.com/owenrumney/go-sarif/blob/8a2f9b473a872089bd8227313c457ea72c53de24/sarif/properties.go#L3) implementations seems to allow arbitrary (json) values while it seems the java implementation is hardcoded to only support the tags property and maybe some I am unfamiliar with (priority, ruleset).

> 2. As for reducing dependencies I am all for it, in fact the first iteration was written without core and re2. I chose re2 in the last minute because it's considered to be bit safe and performant. But since the regex used here are very simple I don't see any issues using re. Using core is bit overkill too, dev dependency is enough. I am happy for you to keep working on this :)

Great! I am glad to hear that :-)

**Comment by reynir** [comment]
Actually, thinking about it a little more I *think* for my purposes it would be fine give special treatment for `tags` as a list of strings. I think all other properties I use (at the moment) are string valued.

**Comment by gborough** [comment]
@reynir There are few alternatives to modelling json field, I can think of two approaches:

1. According to sarif jsonschema, <"additionalProperties": true> is specified on the propertyBag, we can have an optional field like so:
```
type hm_str_str = (string * string) list <json repr="object">
type hm_str_json = (string * Yojson.Basic.t) list <json repr="object">

type property_bag = {
  tags: hm_str_str;
  ?additional_properties: hm_str_json;
}
```
I've seen payloads in the wild that utilise this structure although it forces the producer to use this exact "additional_properties" tag

2. Then according to the sarif specification page as I mentioned before,  the value type can be either json types or string(This is where the frustration kicks in, the spec and jsonschema differs on how it should be properly presented). We can put a enum type on this:
```
type hm_str_strjson = (string * string_or_json) list <json repr="object">
type string_or_json = [
  | StringType of string
  | JsonType of Yojson.Basic.t
]

type property_bag = hm_str_strjson
```

**Comment by reynir** [comment]
I unfortunately don't have experience with how to deal with additionalProperties in atd. At least the `tags` property should be a list of strings:

```atd
type hm_str_json = (string * Yojson.Basic.t) list <json repr="object">

type property_bag = {
  tags: string list;
  ?additional_properties: hm_str_json;
}
```

Re 2: The `string_or_json` type seems unnecessary to me as ``[`String of string] :> Yojson.Basic.t`, that is, `Yojson.Basic.t` already has a constructor for representing string values.

---

In #14 I added test cases with sarif output from Semgrep and implemented propertyBag-as-arbitrary-json. I unfortunately don't know how to enforce the extra constraint on the `tags` property with atd, at least not nicely; you could always add a verification function that checks `tags` properties, but it would be nicer if we could use the type system.

**Comment by gborough** [comment]
https://github.com/gborough/sarif/pull/14 merged
